SchoolManagement/Models/Entity/ExamMark.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SchoolManagement.Model.Entity
{
    public class ExamMark
    {
        private float _total = 0;
        private string _grade = "";
        [Key]
        public int Id { get; set; }

        public float Theory { get; set; }
        public float Mcq { get; set; }
        public float Practical { get; set; }
        public float Total
        {
            get //get method for returning value
            {
                _total = this.Theory + this.Mcq + this.Practical;
                return _total;
            }
            private set // set method for storing value in name field.
            {
                _total = value;
            }
        }
        public string Grade 
        {
            get 
            {
                if (_total >= 80) 
                {
                    return _grade = "A+";
                }
                else if (_total >= 70 && _total < 80)
                {
                    return _grade = "A";
                }
                else if (_total >= 60 && _total < 70)
                {
                    return _grade = "A-";
                }
                else if (_total >= 50 && _total < 60)
                {
                    return _grade = "B";
                }
                else if (_total >= 40 && _total < 50)
                {
                    return _grade = "C";
                }
                else if (_total >= 33 && _total < 40)
                {
                    return _grade = "D";
                }
                else
                    return _grade = "F";
                    
            }
            private set 
            {
                _grade = value;
            }
        }
        public int SubjectId { get; set; }
        public Subject Subject { get; set; }

        public int SessionId { get; set; }
        public Session Session { get; set; }

        public int StudentClassId { get; set; }
        public virtual StudentClass StudentClass { get; set; }

        public int AssignRollId { get; set; }
        public AssignRoll AssignRoll { get; set; }
    }
}

SchoolManagement/Controllers/ExamMarksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SchoolManagement.Model;
using SchoolManagement.Model.Entity;

namespace SchoolManagement.Controllers
{
   // [Authorize(Roles = "Admin, Teacher")]
    public class ExamMarksController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: ExamMarks
        public ActionResult Index()
        {
            var examMark = db.ExamMarks.Include(e => e.Session).Include(e => e.Subject).Include(e => e.StudentClass.ClassName).Include(e => e.AssignRoll);
            return View(examMark.ToList());
        }

        // GET: ExamMarks/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ExamMark examMark = db.ExamMarks.Find(id);
            if (examMark == null)
            {
                return HttpNotFound();
            }
            return View(examMark);
        }

        // GET: ExamMarks/Create
        public ActionResult Create( )
        {
            var studentClass = db.StudentClasses.Select(c => new
            {
                Id = c.Id,
                Name = c.ClassName.Name + " || " + c.Shift.Name + " ||" + c.Section.Name
            }).OrderBy(o => o.Name).ToList();

            ViewBag.SessionId = new SelectList(db.Sessions, "Id", "Name");
            ViewBag.SubjectId = new SelectList(db.Subjects, "Id", "Name");
            ViewBag.StudentClassId = new SelectList(studentClass, "Id", "Name");
            ViewBag.AssignRollId = new SelectList(db.AssignRolls, "Id", "Roll");
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ExamMark examMark)
        {
            if (ModelState.IsValid)
            {
                db.ExamMarks.Add(examMark);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            var studentClass = db.StudentClasses.Select(c => new
            {
                Id = c.Id,
                Name = c.ClassName.Name + " || " + c.Shift.Name + " ||" + c.Section.Name
            }).OrderBy(o => o.Name).ToList();

            ViewBag.SessionId = new SelectList(db.Sessions, "Id", "Name");
            ViewBag.CourseId = new SelectList(db.Subjects, "Id", "Name");
            ViewBag.StudentClassId = new SelectList(studentClass, "Id", "Name");
            ViewBag.AssignRollId = new SelectList(db.AssignRolls, "Id", "Roll");
            return View(examMark);
        }

        // GET: ExamMarks/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ExamMark examMark = db.ExamMarks.Find(id);
            if (examMark == null)
            {
                return HttpNotFound();
            }
            var studentClass = db.StudentClasses.Select(c => new
            {
                Id = c.Id,
                Name = c.ClassName.Name + " || " + c.Shift.Name + " ||" + c.Section.Name
            }).OrderBy(o => o.Name).ToList();

            ViewBag.SessionId = new SelectList(db.Sessions, "Id", "Name");
            ViewBag.CourseId = new SelectList(db.Subjects, "Id", "Name");
            ViewBag.StudentClassId = new SelectList(studentClass, "Id", "Name");
            ViewBag.AssignRollId = new SelectList(db.AssignRolls, "Id", "Roll");
            return View(examMark);
        }

       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ExamMark examMark)
        {
            if (ModelState.IsValid)
            {
                db.Entry(examMark).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            var studentClass = db.StudentClasses.Select(c => new
            {
                Id = c.Id,
                Name = c.ClassName.Name + " || " + c.Shift.Name + " ||" + c.Section.Name
            }).OrderBy(o => o.Name).ToList();

            ViewBag.SessionId = new SelectList(db.Sessions, "Id", "Name");
            ViewBag.CourseId = new SelectList(db.Subjects, "Id", "Name");
            ViewBag.StudentClassId = new SelectList(studentClass, "Id", "Name");
            ViewBag.AssignRollId = new SelectList(db.AssignRolls, "Id", "Roll");
            return View(examMark);
        }

        // GET: ExamMarks/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ExamMark examMark = db.ExamMarks.Find(id);
            if (examMark == null)
            {
                return HttpNotFound();
            }
            return View(examMark);
        }

        // POST: ExamMarks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ExamMark examMark = db.ExamMarks.Find(id);
            db.ExamMarks.Remove(examMark);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SchoolManagement/Views/ExamMarks/Create.cshtml
@model  SchoolManagement.Model.Entity.ExamMark

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="page-header">
    <h1>
        Assign Exam Mark
        <small>
            <i class="ace-icon fa fa-angle-double-right"></i>
            @Html.ActionLink("Back to List", "Index", "ExamMarks", null, new { @class = "btn btn-info" })
        </small>
    </h1>
</div>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.SessionId, "Session", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SessionId", null,"--Select--", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SessionId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StudentClassId, "Student Class", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StudentClassId", null, "--Select--", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SessionId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AssignRollId, "Assign Roll", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("AssignRollId", null, "--Select--", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SessionId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SubjectId, "Course", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SubjectId", null, "--Select--", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SubjectId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Theory, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Theory, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Theory, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mcq, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mcq, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mcq, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Practical, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Practical, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Practical, "", new { @class = "text-danger" })
            </div>
        </div>

       

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>

        $("#StudentClassId").change(function () {
        $.ajax({
            type: "GET",
            url: "/Common/GetRoll",
            data: { session: $('#SessionId').val(), studentClass: $('#StudentClassId').val() },
            datatype: "json",
            traditional: true,
            success: function (data) {
                $("#AssignRollId").empty();
                $.each(data, function (index, row) {

                    $("#AssignRollId").append("<Option value='" + row.Id + "'>" + row.Roll + "</Option>")

                });

            }
        });

        $.ajax({
            type: "GET",
            url: "/Common/GetCourse",
            data: { studentClass: $('#StudentClassId').val() },
            datatype: "json",
            traditional: true,
            success: function (data) {
                $("#CourseId").empty();
                $.each(data, function (index, row) {

                    $("#CourseId").append("<Option value='" + row.Id + "'>" + row.Name + "</Option>")

                });

            }
        });
    });
    </script>
}

SchoolManagement/Views/ExamMarks/Delete.cshtml
@model SchoolManagement.Model.Entity.ExamMark

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ExamMark</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Course.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Course.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Student.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Student.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Theory)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Theory)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Mcq)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mcq)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Practical)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Practical)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Total)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Total)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SchoolManagement/Views/ExamMarks/Details.cshtml
@model SchoolManagement.Model.Entity.ExamMark

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>ExamMark</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Subject.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Subject.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StudentClass.ClassName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StudentClass.ClassName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Theory)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Theory)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Mcq)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mcq)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Practical)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Practical)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Total)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Total)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SchoolManagement/Views/ExamMarks/Edit.cshtml
@model SchoolManagement.Model.Entity.ExamMark

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="page-header">
    <h1>
        Edit Exam Marks
        <small>
            <i class="ace-icon fa fa-angle-double-right"></i>
            @Html.ActionLink("Back to List", "Index", "ExamMarks", null, new { @class = "btn btn-info" })
        </small>
    </h1>
</div>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.SessionId, "Session", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SessionId", null, "--Select--", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SessionId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StudentClassId, "Student Class", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StudentClassId", null, "--Select--", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SessionId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AssignRollId, "Assign Roll", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("AssignRollId", null, "--Select--", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SessionId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SubjectId, "Subject", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Subject", null, "--Select Subject--", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SubjectId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Theory, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Theory, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Theory, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mcq, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mcq, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mcq, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Practical, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Practical, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Practical, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>

        $("#StudentClassId").change(function () {
        $.ajax({
            type: "GET",
            url: "/Common/GetRoll",
            data: { session: $('#SessionId').val(), studentClass: $('#StudentClassId').val() },
            datatype: "json",
            traditional: true,
            success: function (data) {
                $("#AssignRollId").empty();
                $.each(data, function (index, row) {

                    $("#AssignRollId").append("<Option value='" + row.Id + "'>" + row.Roll + "</Option>")

                });

            }
        });

        $.ajax({
            type: "GET",
            url: "/Common/GetCourse",
            data: { studentClass: $('#StudentClassId').val() },
            datatype: "json",
            traditional: true,
            success: function (data) {
                $("#CourseId").empty();
                $.each(data, function (index, row) {

                    $("#CourseId").append("<Option value='" + row.Id + "'>" + row.Name + "</Option>")

                });

            }
        });
    });
    </script>
}

SchoolManagement/Views/ExamMarks/Index.cshtml
@model IEnumerable<SchoolManagement.Model.Entity.ExamMark>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="page-header">
    <h1>
        Exam Mark list
        <small>
            <i class="ace-icon fa fa-angle-double-right"></i>
            @Html.ActionLink("Create New", "Create")
        </small>
    </h1>
</div>
<table class="table">
    <tr>
        <th>
           Session Name
        </th>
        <th>
           Class Name
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AssignRoll.Roll)
        </th>
        <th>
           Subject Name
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Theory)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Mcq)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Practical)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Total)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Grade)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Session.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StudentClass.ClassName.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AssignRoll.Roll)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Subject.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Theory)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Mcq)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Practical)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Total)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Grade)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>