SchoolManagement/Models/Entity/ExamTitle.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SchoolManagement.Model.Entity
{
    public class ExamTitle
    {
        [Key]
        public int Id { get; set; }

        [Display(Name = "Title Name")]
        [Required(ErrorMessage = "Required!")]
        public string TitleName { get; set; }


        public int EducationLevelId { get; set; }

        public EducationLevel EducationLevel { get; set; }
    }
}

SchoolManagement/Controllers/ExamTitlesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SchoolManagement.Model;
using SchoolManagement.Model.Entity;

namespace SchoolManagement.Controllers
{
   // [Authorize(Roles = "Admin")]
    public class ExamTitlesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

       
        public ActionResult Index()
        {
            var examTitle = db.ExamTitles.Include(e => e.EducationLevel);
            return View(examTitle.ToList());
        }

       
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ExamTitle examTitle = db.ExamTitles.Find(id);
            if (examTitle == null)
            {
                return HttpNotFound();
            }
            return View(examTitle);
        }
        public ActionResult Create()
        {
            ViewBag.EducationLevelId = new SelectList(db.EducationLevels, "Id", "EducationLevelNaame");
            return View();
        }

       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ExamTitle examTitle)
        {
            if (ModelState.IsValid)
            {
                db.ExamTitles.Add(examTitle);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.EducationLevelId = new SelectList(db.EducationLevels, "Id", "EducationLevelNaame", examTitle.EducationLevelId);
            return View(examTitle);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ExamTitle examTitle = db.ExamTitles.Find(id);
            if (examTitle == null)
            {
                return HttpNotFound();
            }
            ViewBag.EducationLevelId = new SelectList(db.EducationLevels, "Id", "EducationLevelNaame", examTitle.EducationLevelId);
            return View(examTitle);
        }

       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ExamTitle examTitle)
        {
            if (ModelState.IsValid)
            {
                db.Entry(examTitle).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.EducationLevelId = new SelectList(db.EducationLevels, "Id", "EducationLevelNaame", examTitle.EducationLevelId);
            return View(examTitle);
        }

        
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ExamTitle examTitle = db.ExamTitles.Find(id);
            if (examTitle == null)
            {
                return HttpNotFound();
            }
            return View(examTitle);
        }

       
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ExamTitle examTitle = db.ExamTitles.Find(id);
            db.ExamTitles.Remove(examTitle);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SchoolManagement/Views/ExamTitles/Create.cshtml
@model SchoolManagement.Models.Entity.ExamTitle

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="page-header">
    <h1>
        Add New Exam Title
        <small>
            <i class="ace-icon fa fa-angle-double-right"></i>
            @Html.ActionLink("Back to List", "Index", "ExamTitles", null, new { @class = "btn btn-info" })
        </small>
    </h1>
</div>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.TitleName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TitleName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TitleName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EducationLevelId, "Education Level", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("EducationLevelId", null,"--Select--", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EducationLevelId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-info" />
            </div>
        </div>
    </div>
}

SchoolManagement/Views/ExamTitles/Delete.cshtml
@model SchoolManagement.Models.Entity.ExamTitle

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="page-header">
    <h1>
        Are you sure you want to delete this?
        <small>
            <i class="ace-icon fa fa-angle-double-right"></i>
            @Html.ActionLink("Back to List", "Index")
        </small>
    </h1>
</div>
<div>
    
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.EducationLevel.EducationLevelNaame)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EducationLevel.EducationLevelNaame)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TitleName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TitleName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" />
        </div>
    }
</div>

SchoolManagement/Views/ExamTitles/Details.cshtml
@model SchoolManagement.Models.Entity.ExamTitle

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="page-header">
    <h1>
        Details of a Session
        <small>
            <i class="ace-icon fa fa-angle-double-right"></i>
            @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
            @Html.ActionLink("Back to List", "Index")
        </small>
    </h1>
</div>

<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.EducationLevel.EducationLevelNaame)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EducationLevel.EducationLevelNaame)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TitleName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TitleName)
        </dd>

    </dl>
</div>

SchoolManagement/Views/ExamTitles/Edit.cshtml
@model SchoolManagement.Models.Entity.ExamTitle

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="page-header">
    <h1>
        Edit Exam Title
        <small>
            <i class="ace-icon fa fa-angle-double-right"></i>
            @Html.ActionLink("Back to List", "Index", "ExamTitles", null, new { @class = "btn btn-info" })
        </small>
    </h1>
</div>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.TitleName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TitleName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TitleName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EducationLevelId, "Education Level", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("EducationLevelId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EducationLevelId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

SchoolManagement/Views/ExamTitles/Index.cshtml
@model IEnumerable<SchoolManagement.Models.Entity.ExamTitle>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="page-header">
    <h1>
        Exam Title list
        <small>
            <i class="ace-icon fa fa-angle-double-right"></i>
            @Html.ActionLink("Create New", "Create")
        </small>
    </h1>
</div>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.EducationLevel.EducationLevelNaame)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TitleName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.EducationLevel.EducationLevelNaame)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TitleName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>